// Emits src/api/textLimit.ts from the OpenAPI document, so the interface enforces the same
// bounds as the API instead of restating them.
//
// The numbers originate in backend/src/text_limit.ts, travel through the Zod request schemas
// into open-api.json, and land here. Orval already carries them across but writes them as
// JSDoc comments, which nothing can read at runtime.
//
// Output goes into src/api/, which is gitignored: the file is rebuilt from the document on
// every generation and never committed, so it cannot go stale.
//
// Run by Node's own type stripping — no build step and no runner. That erases types without
// checking them, so `tsconfig.node.json` covers this file for `vue-tsc --build`, and its
// `erasableSyntaxOnly` rejects the syntax stripping cannot handle (enum, namespace,
// parameter properties) at check time rather than at run time.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/** Only the corner of OpenAPI this reads. Request bodies are inline — there are no $refs. */
type Bound = { minLength?: number; maxLength?: number }

type Operation = {
  operationId?: string
  requestBody?: {
    content?: Record<string, { schema?: { properties?: Record<string, Bound> } }>
  }
}

type OpenApiDocument = { paths: Record<string, Record<string, Operation | undefined>> }

const here = dirname(fileURLToPath(import.meta.url))
const SPECIFICATION = resolve(here, '../../backend/open-api.json')
const OUTPUT = resolve(here, '../src/api/textLimit.ts')

const specification = JSON.parse(readFileSync(SPECIFICATION, 'utf8')) as OpenApiDocument

function boundsOf(operation: Operation): Record<string, Bound> {
  const schema = operation.requestBody?.content?.['application/json']?.schema
  const bounds: Record<string, Bound> = {}

  for (const [property, definition] of Object.entries(schema?.properties ?? {})) {
    const bound: Bound = {}
    if (typeof definition.minLength === 'number') bound.minLength = definition.minLength
    if (typeof definition.maxLength === 'number') bound.maxLength = definition.maxLength
    if (Object.keys(bound).length > 0) bounds[property] = bound
  }

  return bounds
}

const operations: Record<string, Record<string, Bound>> = {}
for (const methods of Object.values(specification.paths)) {
  for (const operation of Object.values(methods)) {
    if (operation?.operationId === undefined) continue
    const bounds = boundsOf(operation)
    if (Object.keys(bounds).length > 0) operations[operation.operationId] = bounds
  }
}

const body = Object.entries(operations)
  .map(([operationId, properties]) => {
    const lines = Object.entries(properties).map(([property, bound]) => {
      const parts = Object.entries(bound).map(([key, value]) => `${key}: ${value}`)
      return `    ${property}: { ${parts.join(', ')} },`
    })
    return `  ${operationId}: {\n${lines.join('\n')}\n  },`
  })
  .join('\n')

writeFileSync(
  OUTPUT,
  `/**
 * Generated by scripts/generateTextLimit.ts from backend/open-api.json.
 * Do not edit — change backend/src/text_limit.ts instead.
 *
 * Keyed by operation and request-body property, which is the granularity an input needs:
 * \`createGroup.title\` and \`createThread.title\` are separate bounds that happen to agree.
 */
export const TEXT_LIMIT = {
${body}
} as const
`,
)

console.log(`Wrote ${Object.keys(operations).length} operations to src/api/textLimit.ts`)
