// Emits src/api/textLimit.ts from the OpenAPI document, so the interface enforces the same
// bounds as the API instead of restating them.
//
// The numbers originate in backend/src/text_limit.ts, travel through the Zod request schemas
// into open-api.json, and land here. Orval already carries them across but writes them as
// JSDoc comments, which nothing can read at runtime.
//
// Output goes into src/api/, which is gitignored: the file is rebuilt from the document on
// every generation and never committed, so it cannot go stale.
//
// Run by Node's own type stripping — no build step and no runner. That erases types without
// checking them, so `tsconfig.node.json` covers this file for `vue-tsc --build`, and its
// `erasableSyntaxOnly` rejects the syntax stripping cannot handle (enum, namespace,
// parameter properties) at check time rather than at run time.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

/** Only the corner of OpenAPI this reads. Request bodies are inline — there are no $refs. */
type Bound = { minLength?: number; maxLength?: number }

type Schema = {
  properties?: Record<string, Bound>
  oneOf?: Schema[]
  anyOf?: Schema[]
}

type Operation = {
  operationId?: string
  requestBody?: { content?: Record<string, { schema?: Schema }> }
}

type OpenApiDocument = { paths: Record<string, Record<string, Operation | undefined>> }

const here = import.meta.dirname
const SPECIFICATION = resolve(here, '../../backend/open-api.json')
const OUTPUT = resolve(here, '../src/api/textLimit.ts')

const specification = JSON.parse(readFileSync(SPECIFICATION, 'utf8')) as OpenApiDocument

/**
 * Bounds from a schema and from every branch of a union, because a `oneOf` body keeps its
 * properties inside the branches rather than at the top — `moveReport`'s does. Reading only the top
 * level produced no bounds at all for such an operation, silently, which is the one failure this
 * file exists to prevent.
 *
 * A property in more than one branch has to agree with itself: `note` appears in both the reopening
 * and the closing. Branches that disagreed would make the number written here a guess about which
 * one an input is for, so that fails loudly instead.
 */
function collectBounds(
  schema: Schema | undefined,
  operationId: string,
  into: Record<string, Bound>,
): void {
  if (schema === undefined) return

  for (const [property, definition] of Object.entries(schema.properties ?? {})) {
    const bound: Bound = {}
    if (typeof definition.minLength === 'number') bound.minLength = definition.minLength
    if (typeof definition.maxLength === 'number') bound.maxLength = definition.maxLength
    if (Object.keys(bound).length === 0) continue

    const existing = into[property]
    if (existing !== undefined && JSON.stringify(existing) !== JSON.stringify(bound)) {
      throw new Error(
        `${operationId}.${property} is bounded two ways across the branches of its request body: ` +
          `${JSON.stringify(existing)} and ${JSON.stringify(bound)}`,
      )
    }

    into[property] = bound
  }

  for (const branch of [...(schema.oneOf ?? []), ...(schema.anyOf ?? [])]) {
    collectBounds(branch, operationId, into)
  }
}

function boundsOf(operation: Operation, operationId: string): Record<string, Bound> {
  const bounds: Record<string, Bound> = {}
  collectBounds(operation.requestBody?.content?.['application/json']?.schema, operationId, bounds)
  return bounds
}

const operations: Record<string, Record<string, Bound>> = {}
for (const methods of Object.values(specification.paths)) {
  for (const operation of Object.values(methods)) {
    if (operation?.operationId === undefined) continue
    const bounds = boundsOf(operation, operation.operationId)
    if (Object.keys(bounds).length > 0) operations[operation.operationId] = bounds
  }
}

const body = Object.entries(operations)
  .map(([operationId, properties]) => {
    const lines = Object.entries(properties).map(([property, bound]) => {
      const parts = Object.entries(bound).map(([key, value]) => `${key}: ${value}`)
      return `    ${property}: { ${parts.join(', ')} },`
    })
    return `  ${operationId}: {\n${lines.join('\n')}\n  },`
  })
  .join('\n')

writeFileSync(
  OUTPUT,
  `/**
 * Generated by scripts/generateTextLimit.ts from backend/open-api.json.
 * Do not edit — change backend/src/text_limit.ts instead.
 *
 * Keyed by operation and request-body property, which is the granularity an input needs:
 * \`createGroup.title\` and \`createThread.title\` are separate bounds that happen to agree.
 */
export const TEXT_LIMIT = {
${body}
} as const
`,
)

console.log(`Wrote ${Object.keys(operations).length} operations to src/api/textLimit.ts`)
