/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type UserInWritingGroupRole = "administrator" | "reader" | "writer";

export type UserInWritingGroupStatus = "invited" | "joined";

export type WritingGroupVisibility = "private" | "public";

export interface Post {
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  isDraft: boolean;
  text: string;
  threadId: string;
  updatedAt: Generated<string>;
}

export interface Thread {
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  lastActivityAt: Generated<string>;
  title: string;
  updatedAt: Generated<string>;
  writingGroupId: string;
}

export interface User {
  createdAt: Generated<string>;
  emailAddress: string;
  hashedPassword: string;
  id: Generated<string>;
  updatedAt: Generated<string>;
  username: string;
}

export interface UserInWritingGroup {
  createdAt: Generated<string>;
  role: UserInWritingGroupRole;
  status: UserInWritingGroupStatus;
  updatedAt: Generated<string>;
  userId: string;
  writingGroupId: string;
}

export interface UserSession {
  createdAt: Generated<string>;
  expiresAt: string;
  hashedToken: Buffer;
  id: Generated<string>;
  updatedAt: Generated<string>;
  userId: string;
}

export interface WritingGroup {
  createdAt: Generated<string>;
  createdBy: string | null;
  description: string;
  id: Generated<string>;
  lastActivityAt: Generated<string>;
  title: string;
  updatedAt: Generated<string>;
  visibility: Generated<WritingGroupVisibility>;
}

export interface DB {
  post: Post;
  thread: Thread;
  user: User;
  userInWritingGroup: UserInWritingGroup;
  userSession: UserSession;
  writingGroup: WritingGroup;
}
import * as z from "zod";

export const WRITING_GROUP_VISIBILITIES = ["private", "public"] as const;
export const WRITING_GROUP_VISIBILITY_SCHEMA = z.enum(
  WRITING_GROUP_VISIBILITIES,
);

export const USER_IN_WRITING_GROUP_ROLES = [
  "administrator",
  "reader",
  "writer",
] as const;
export const USER_IN_WRITING_GROUP_ROLE_SCHEMA = z.enum(
  USER_IN_WRITING_GROUP_ROLES,
);

export const USER_IN_WRITING_GROUP_STATUSES = ["invited", "joined"] as const;
export const USER_IN_WRITING_GROUP_STATUS_SCHEMA = z.enum(
  USER_IN_WRITING_GROUP_STATUSES,
);

export const POST_SCHEMA = z.object({
  id: z.uuidv7(),
  threadId: z.uuidv7(),
  text: z.string(),
  isDraft: z.boolean(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});

export const THREAD_SCHEMA = z.object({
  id: z.uuidv7(),
  writingGroupId: z.uuidv7(),
  title: z.string(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
});

export const USER_SCHEMA = z.object({
  id: z.uuidv7(),
  username: z.string(),
  hashedPassword: z.string(),
  emailAddress: z.string(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});

export const USER_IN_WRITING_GROUP_SCHEMA = z.object({
  userId: z.uuidv7(),
  writingGroupId: z.uuidv7(),
  role: USER_IN_WRITING_GROUP_ROLE_SCHEMA,
  status: USER_IN_WRITING_GROUP_STATUS_SCHEMA,
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});

export const USER_SESSION_SCHEMA = z.object({
  id: z.uuidv7(),
  userId: z.uuidv7(),
  hashedToken: z.instanceof(Uint8Array),
  expiresAt: z.iso.datetime({ offset: true }),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});

export const WRITING_GROUP_SCHEMA = z.object({
  id: z.uuidv7(),
  title: z.string(),
  description: z.string(),
  visibility: WRITING_GROUP_VISIBILITY_SCHEMA,
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
});
