/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type NotificationType =
  | "invitation_accepted"
  | "invited_to_chat_group"
  | "invited_to_writing_group"
  | "new_writing_post"
  | "new_writing_thread"
  | "role_changed_in_writing_group"
  | "visibility_changed_in_writing_group";

export type UserInChatGroupStatus = "invited" | "joined";

export type UserInWritingGroupRole = "administrator" | "reader" | "writer";

export type UserInWritingGroupStatus = "invited" | "joined";

export type WritingGroupVisibility = "private" | "public";

export interface ChatGroup {
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  lastActivityAt: Generated<string>;
  title: string;
}

export interface ChatMessage {
  chatGroupId: string;
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  text: string;
}

export interface Notification {
  actorId: string | null;
  chatGroupId: string | null;
  createdAt: Generated<string>;
  id: Generated<string>;
  occurredAt: Generated<string>;
  readAt: string | null;
  recipientId: string;
  type: NotificationType;
  writingGroupId: string | null;
  writingPostId: string | null;
  writingThreadId: string | null;
}

export interface User {
  createdAt: Generated<string>;
  emailAddress: string;
  hashedPassword: string;
  id: Generated<string>;
  updatedAt: Generated<string>;
  username: string;
}

export interface UserInChatGroup {
  chatGroupId: string;
  createdAt: Generated<string>;
  invitedAt: string | null;
  joinedAt: string | null;
  lastReadAt: string | null;
  status: UserInChatGroupStatus;
  userId: string;
}

export interface UserInWritingGroup {
  createdAt: Generated<string>;
  invitedAt: string | null;
  invitedBy: string | null;
  joinedAt: string | null;
  role: UserInWritingGroupRole;
  status: UserInWritingGroupStatus;
  userId: string;
  writingGroupId: string;
}

export interface UserSession {
  createdAt: Generated<string>;
  expiresAt: string;
  hashedToken: Buffer;
  id: Generated<string>;
  updatedAt: Generated<string>;
  userId: string;
}

export interface WritingGroup {
  createdAt: Generated<string>;
  createdBy: string | null;
  description: string;
  id: Generated<string>;
  lastActivityAt: Generated<string>;
  title: string;
  visibility: Generated<WritingGroupVisibility>;
}

export interface WritingPost {
  createdAt: Generated<string>;
  createdBy: string | null;
  editedAt: string | null;
  id: Generated<string>;
  isDraft: boolean;
  text: string;
  writingThreadId: string;
}

export interface WritingThread {
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  lastActivityAt: Generated<string>;
  title: string;
  writingGroupId: string;
}

export interface DB {
  chatGroup: ChatGroup;
  chatMessage: ChatMessage;
  notification: Notification;
  user: User;
  userInChatGroup: UserInChatGroup;
  userInWritingGroup: UserInWritingGroup;
  userSession: UserSession;
  writingGroup: WritingGroup;
  writingPost: WritingPost;
  writingThread: WritingThread;
}
import * as z from "zod";

export const WRITING_GROUP_VISIBILITIES = ["private", "public"] as const;
export const WRITING_GROUP_VISIBILITY_SCHEMA = z.enum(
  WRITING_GROUP_VISIBILITIES,
);

export const USER_IN_WRITING_GROUP_ROLES = [
  "administrator",
  "reader",
  "writer",
] as const;
export const USER_IN_WRITING_GROUP_ROLE_SCHEMA = z.enum(
  USER_IN_WRITING_GROUP_ROLES,
);

export const USER_IN_WRITING_GROUP_STATUSES = ["invited", "joined"] as const;
export const USER_IN_WRITING_GROUP_STATUS_SCHEMA = z.enum(
  USER_IN_WRITING_GROUP_STATUSES,
);

export const USER_IN_CHAT_GROUP_STATUSES = ["invited", "joined"] as const;
export const USER_IN_CHAT_GROUP_STATUS_SCHEMA = z.enum(
  USER_IN_CHAT_GROUP_STATUSES,
);

export const NOTIFICATION_TYPES = [
  "invitation_accepted",
  "invited_to_chat_group",
  "invited_to_writing_group",
  "new_writing_post",
  "new_writing_thread",
  "role_changed_in_writing_group",
  "visibility_changed_in_writing_group",
] as const;
export const NOTIFICATION_TYPE_SCHEMA = z.enum(NOTIFICATION_TYPES);

export const CHAT_GROUP_SCHEMA = z.object({
  id: z.uuidv7(),
  title: z.string(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
});

export const CHAT_MESSAGE_SCHEMA = z.object({
  id: z.uuidv7(),
  chatGroupId: z.uuidv7(),
  text: z.string(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const NOTIFICATION_SCHEMA = z.object({
  id: z.uuidv7(),
  recipientId: z.uuidv7(),
  type: NOTIFICATION_TYPE_SCHEMA,
  actorId: z.uuidv7().nullable(),
  writingGroupId: z.uuidv7().nullable(),
  chatGroupId: z.uuidv7().nullable(),
  writingThreadId: z.uuidv7().nullable(),
  writingPostId: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  occurredAt: z.iso.datetime({ offset: true }),
  readAt: z.iso.datetime({ offset: true }).nullable(),
});

export const USER_SCHEMA = z.object({
  id: z.uuidv7(),
  username: z.string(),
  hashedPassword: z.string(),
  emailAddress: z.string(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});

export const USER_IN_CHAT_GROUP_SCHEMA = z.object({
  userId: z.uuidv7(),
  chatGroupId: z.uuidv7(),
  status: USER_IN_CHAT_GROUP_STATUS_SCHEMA,
  invitedAt: z.iso.datetime({ offset: true }).nullable(),
  joinedAt: z.iso.datetime({ offset: true }).nullable(),
  lastReadAt: z.iso.datetime({ offset: true }).nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const USER_IN_WRITING_GROUP_SCHEMA = z.object({
  userId: z.uuidv7(),
  writingGroupId: z.uuidv7(),
  role: USER_IN_WRITING_GROUP_ROLE_SCHEMA,
  status: USER_IN_WRITING_GROUP_STATUS_SCHEMA,
  invitedAt: z.iso.datetime({ offset: true }).nullable(),
  joinedAt: z.iso.datetime({ offset: true }).nullable(),
  invitedBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const USER_SESSION_SCHEMA = z.object({
  id: z.uuidv7(),
  userId: z.uuidv7(),
  hashedToken: z.instanceof(Uint8Array),
  expiresAt: z.iso.datetime({ offset: true }),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});

export const WRITING_GROUP_SCHEMA = z.object({
  id: z.uuidv7(),
  title: z.string(),
  description: z.string(),
  visibility: WRITING_GROUP_VISIBILITY_SCHEMA,
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
});

export const WRITING_POST_SCHEMA = z.object({
  id: z.uuidv7(),
  writingThreadId: z.uuidv7(),
  text: z.string(),
  isDraft: z.boolean(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  editedAt: z.iso.datetime({ offset: true }).nullable(),
});

export const WRITING_THREAD_SCHEMA = z.object({
  id: z.uuidv7(),
  writingGroupId: z.uuidv7(),
  title: z.string(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
});
